[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "更自由、更强大的StringBuilder工具类"
  link-option = ""
  name = "stringbuilder"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "0.2.1"
  [package.package-configuration]
  [package.scripts]
