[dependencies]

[package]
  cjc-version = "1.0.1"
  compile-option = ""
  description = ""
  link-option = ""
  name = "whatlang4cj"
  output-type = "static"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
