[package]
  cjc-version = "1.0.0"
  name = "morerandom"
  description = "随机数库"
  version = "0.1.4"
  target-dir = ""
  src-dir = ""
  output-type = "executable"
  compile-option = "-Woff unused"
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
