[dependencies]

[package]
  cjc-version = "1.0.0"
  compile-option = ""
  description = "SQL script builder"
  link-option = ""
  name = "sql_builder"
  output-type = "static"
  src-dir = "src"
  target-dir = ""
  version = "1.0.4"
  package-configuration = {}

# 需要将stdx依赖路径添加到环境变量CANGJIE_STDX_PATH中

[target.x86_64-w64-mingw32]                                                   
  compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -lcrypt32"
  [target.x86_64-w64-mingw32.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]

[target.x86_64-unknown-linux-gnu]
  compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -ldl"
  [target.x86_64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]

[target.aarch64-unknown-linux-gnu]
  compile-option = "-Woff unused --diagnostic-format=noColor -Woff deprecated -ldl"
  [target.aarch64-unknown-linux-gnu.bin-dependencies]
    path-option = ["${CANGJIE_STDX_PATH}"]